//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoozballBets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factor
    {
        public int FactorId { get; set; }
        public int MatchId { get; set; }
        public decimal Win1 { get; set; }
        public decimal X { get; set; }
        public decimal Win2 { get; set; }
    
        public virtual Match Match { get; set; }
    }
}
