//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoozballBets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        public Match()
        {
            this.Bets = new HashSet<Bet>();
            this.Factors = new HashSet<Factor>();
        }
    
        public int MatchId { get; set; }
        public string MatchResult { get; set; }
        public int Team1Id { get; set; }
        public int Team2Id { get; set; }
        public string MatchName { get; set; }
        public Nullable<int> MatchDate { get; set; }
        public Nullable<bool> IsPlayed { get; set; }
    
        public virtual ICollection<Bet> Bets { get; set; }
        public virtual ICollection<Factor> Factors { get; set; }
        public virtual Team Team { get; set; }
        public virtual Team Team1 { get; set; }
    }
}
