//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoozballBets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfilesBSH
    {
        public ProfilesBSH()
        {
            this.Bets = new HashSet<Bet>();
            this.TeamBets = new HashSet<TeamBet>();
        }
    
        public int ProfileId { get; set; }
        public string ProfilePicPath { get; set; }
        public int Points { get; set; }
        public string Name { get; set; }
        public System.Guid UserId { get; set; }
        public int TeamId { get; set; }
        public Nullable<int> ProfileWins { get; set; }
        public Nullable<int> ProfileLoses { get; set; }
    
        public virtual ICollection<Bet> Bets { get; set; }
        public virtual Team Team { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<TeamBet> TeamBets { get; set; }
    }
}
