//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoozballBets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamBet
    {
        public int TeamBetsId { get; set; }
        public int BetValue { get; set; }
        public int TeamId { get; set; }
        public int ProfileId { get; set; }
        public Nullable<System.DateTime> BetDate { get; set; }
    
        public virtual ProfilesBSH ProfilesBSH { get; set; }
        public virtual Team Team { get; set; }
    }
}
