//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoozballBets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public Team()
        {
            this.Matches = new HashSet<Match>();
            this.Matches1 = new HashSet<Match>();
            this.ProfilesBSHes = new HashSet<ProfilesBSH>();
            this.TeamBets = new HashSet<TeamBet>();
        }
    
        public int TeamId { get; set; }
        public string TeamName { get; set; }
        public int TeamWins { get; set; }
        public int TeamLoses { get; set; }
        public int TeamDraws { get; set; }
        public Nullable<decimal> TeamFactor { get; set; }
    
        public virtual ICollection<Match> Matches { get; set; }
        public virtual ICollection<Match> Matches1 { get; set; }
        public virtual ICollection<ProfilesBSH> ProfilesBSHes { get; set; }
        public virtual ICollection<TeamBet> TeamBets { get; set; }
    }
}
